[package]
name = "grep"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2"
walkdir = "2"
regex = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[[test]]
name = "cli"
path = "itests/cli.rs"
